cloud:
  aws:
    credentials:
      accessKey: AKIAUWHV7TRVS5H3W5CF
      secretKey: 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
      instanceProfile: true
    s3:
      bucket: sulgibucket
    region:
      static: ap-northeast-2
    stack:
      auto: false




